### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/data.option'

### ISSUE THREAD

**Issue by SeekPoint** [HKUST-KnowComp/Deepgraphcnn#2]
mldl@ub1604:~/ub16_prj/DeepGraphCNNforTexts$ python3 graphcnn_train.py
Traceback (most recent call last):
  File "graphcnn_train.py", line 205, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "graphcnn_train.py", line 187, in main
    ont_hot=True,index_mode=True)
  File "/home/mldl/ub16_prj/DeepGraphCNNforTexts/graphcnn_input.py", line 422, in generate_train_data
    fr = open(filename, 'w')
FileNotFoundError: [Errno 2] No such file or directory: './data/data.option'
mldl@ub1604:~/ub16_prj/DeepGraphCNNforTexts$

**Comment by yhbelieve** [comment]
作者您好，我运行您的代码，发现很多./tmp/graphcnn_train这种类似的文件或者文件夹都不存在，我在代码中也没看到如何通过rcv1数据集生成相应的数据，希望作者在百忙之中抽出时间，解决一下我的疑问，谢谢啦

**Comment by kevinew** [comment]
Hi guys, I meet the same problem , why can't find the data folder?

**Comment by yanfan0531** [comment]
Same problem here.

**Comment by jingchaoqi** [comment]
Same problem, can anybody help us? Thaks a lot.
